### ISSUE TITLE
Floats for ticks

### ISSUE THREAD

**Issue by fedorn** [marcharper/python-ternary#79]
I've found that 1.0.3 version converts all float ticks to integer which cause example examples/color_coded_heatmap.py to produce ticks 0,0,0,0,0,0,0,0,0,0,1 instead of 0.0,0.1,0.2,...1.0. This does not happen in version 1.0.1.

**Comment by fedorn** [comment]
I figured that tick_formats="%.1f" argument should be added to tax.ticks to fix the problem. I'm keeping this issue open because example code should be fixed.

**Comment by marcharper** [comment]
This sounds like a change in matplotlib, I don't recall any explicit changes that would have caused this. I'm not opposed to changing the defaults, but this is more of a preference than an issue IMO.

**Comment by fedorn** [comment]
The change is here https://github.com/marcharper/python-ternary/commit/4f5dab68d5aa4f1918937e22c8b2e47cf5dcdc4c#diff-812376a19bf7f47735f8b85a2b0bcc40L261. Look at line 272: s = str(int(tick)). I don't oppose keeping it, but lines 34,35 in examples/color_coded_heatmap.py should be updated accordingly (tick_formats in line 35 should be used instead of round() in line 34).

**Comment by fedorn** [comment]
Here's the diff
```diff
diff --git a/examples/color_coded_heatmap.py b/examples/color_coded_heatmap.py
index 3f459de..d24c9b6 100644
--- a/examples/color_coded_heatmap.py
+++ b/examples/color_coded_heatmap.py
@@ -31,9 +31,9 @@ tax.gridlines(multiple=1, linewidth=2,
               right_kwargs={'color':axes_colors['r']},
               alpha=0.7)
 
-ticks = [round(i / float(scale), 1) for i in range(scale+1)]
+ticks = [i / float(scale) for i in range(scale+1)]
 tax.ticks(ticks=ticks, axis='rlb', linewidth=1, clockwise=True,
-          axes_colors=axes_colors, offset=0.03)
+          axes_colors=axes_colors, offset=0.03, tick_formats="%.1f")
 
 tax.clear_matplotlib_ticks()
 
```

**Comment by marcharper** [comment]
Thanks. Feel free to submit a pull request, otherwise I'll fix it within a few days.

**Comment by chengrunyang** [comment]
Hi, has this been fixed? I am still getting ticks like 0,0,0,0,0,0,0,0,0,0,1 instead of 0.0,0.1,0.2,...1.0. The python-ternary version I have installed is 1.0.4.

**Comment by marcharper** [comment]
I just pushed a new release (1.0.5) that contains the fix.

**Comment by chengrunyang** [comment]
I upgraded my installation by pip but the problem still seems to occur. An example, which is a slight modification of your demo, is as follows:

`import ternary
import random
from matplotlib import pyplot as plt

def random_points(num_points=25, scale=40):
    points = []
    for i in range(num_points):
        x = random.randint(1, scale)
        y = random.randint(0, scale - x)
        z = scale - x - y
        points.append((x, y, z))
    return points

### Scatter Plot
scale=1
fontsize=20
fig, ax = plt.subplots(figsize=(12, 10.4))
plt.axis('off')
tax = ternary.TernaryAxesSubplot(ax=ax, scale=scale)
# tax.set_title("Scatter Plot", fontsize=fontsize)
tax.boundary(linewidth=2.0)
tax.gridlines(multiple=0.1, color="blue")
# Plot a few different styles with a legend
points = random_points(2, scale=scale)
print(points)
tax.scatter(points, s=100, marker='D', color='green', label="Green Diamonds")

tax.ticks(axis='lbr', linewidth=1, multiple=0.1)
tax.clear_matplotlib_ticks()
tax.show()`

This produces the following plot:
![image](https://user-images.githubusercontent.com/8860197/50035696-aa95ec80-ffd1-11e8-89e4-6f2fe4c6a1f6.png)

**Comment by marcharper** [comment]
You have to pass in a formatting argument:
`tax.ticks(axis='lbr', linewidth=1, multiple=0.1, tick_formats="%.1f")`

I'll consider trying to detect if non-integer tick formats can be inferred from the other arguments.

![image](https://user-images.githubusercontent.com/203345/50044673-01d0a700-003c-11e9-9f63-a7cdd96513db.png)

**Comment by marcharper** [comment]
I'll update the examples to indicate this. Thanks for the report!
